"""
mcp_tools.py
============
Model Context Protocol (MCP) Tools for Project Tara:
- Robinhood Portfolio & Trade Simulation
- Solana Agent Actions
- Quantitative 30-Day Regression Data
"""

import json
from data_science_rag import get_market_data_and_rag_context
from solana_agent import SolanaAgentEngine

solana_agent = SolanaAgentEngine()

# Simulated Robinhood Store (persists during active session or connects to robin_stocks)
ROBINHOOD_SANDBOX = {
    "cash_balance": 10000.00,
    "portfolio": {
        "AAPL": {"shares": 10, "avg_cost": 175.00},
        "NVDA": {"shares": 15, "avg_cost": 120.00}
    },
    "trade_history": []
}

MCP_TOOL_DEFINITIONS = [
    {
        "name": "get_30d_log_regression",
        "description": "Calculates Tara's mathematical 30-day fair-value baseline for any stock or crypto.",
        "parameters": {
            "type": "object",
            "properties": {
                "symbol": {"type": "string", "description": "Stock ticker (e.g. AAPL, NVDA, SOL, BTC)"}
            },
            "required": ["symbol"]
        }
    },
    {
        "name": "robinhood_execute_trade",
        "description": "Executes or simulates a buy/sell trade on Robinhood with risk check guardrails.",
        "parameters": {
            "type": "object",
            "properties": {
                "ticker": {"type": "string", "description": "Ticker symbol to trade"},
                "action": {"type": "string", "enum": ["BUY", "SELL"]},
                "shares": {"type": "number", "description": "Number of shares"}
            },
            "required": ["ticker", "action", "shares"]
        }
    },
    {
        "name": "solana_agentic_dca",
        "description": "Autonomously executes a Dollar-Cost-Averaging payment/transfer on Solana Devnet.",
        "parameters": {
            "type": "object",
            "properties": {
                "destination_wallet": {"type": "string", "description": "Recipient Devnet wallet address"},
                "sol_amount": {"type": "number", "description": "Amount of Devnet SOL to transfer"}
            },
            "required": ["destination_wallet", "sol_amount"]
        }
    },
    {
        "name": "solana_record_attestation",
        "description": "Records Tara's quantitative investment analysis on-chain via the Solana Memo program.",
        "parameters": {
            "type": "object",
            "properties": {
                "symbol": {"type": "string"},
                "baseline_price": {"type": "number"},
                "advice": {"type": "string"}
            },
            "required": ["symbol", "baseline_price", "advice"]
        }
    }
]

def execute_mcp_tool(tool_name: str, arguments: dict) -> dict:
    """Dispatches tool calls generated by Tara's Agent."""
    if tool_name == "get_30d_log_regression":
        sym = arguments.get("symbol", "AAPL")
        data = get_market_data_and_rag_context(sym)
        if not data:
            return {"error": f"No data for {sym}"}
        return {
            "symbol": data["symbol"],
            "current_price": data["current_price"],
            "fair_trend_price": data["trend_price_today"],
            "percent_diff": data["percent_diff"],
            "recommendation": data["position"]
        }

    elif tool_name == "robinhood_execute_trade":
        ticker = arguments.get("ticker", "").upper()
        action = arguments.get("action", "BUY").upper()
        shares = float(arguments.get("shares", 1.0))
        
        # Pull live price
        mkt = get_market_data_and_rag_context(ticker)
        price = mkt["current_price"] if mkt else 100.0
        total_cost = round(price * shares, 2)

        if action == "BUY":
            if ROBINHOOD_SANDBOX["cash_balance"] < total_cost:
                return {"status": "error", "message": "Insufficient Robinhood purchasing power."}
            RORobinhood_cash = ROBINHOOD_SANDBOX["cash_balance"] - total_cost
            ROBINHOOD_SANDBOX["cash_balance"] = round(RORobinhood_cash, 2)
            
            # Update holdings
            curr_pos = ROBINHOOD_SANDBOX["portfolio"].get(ticker, {"shares": 0, "avg_cost": 0.0})
            new_shares = curr_pos["shares"] + shares
            new_cost = round(((curr_pos["shares"] * curr_pos["avg_cost"]) + total_cost) / new_shares, 2)
            ROBINHOOD_SANDBOX["portfolio"][ticker] = {"shares": new_shares, "avg_cost": new_cost}
        else:
            if ticker not in ROBINHOOD_SANDBOX["portfolio"] or ROBINHOOD_SANDBOX["portfolio"][ticker]["shares"] < shares:
                return {"status": "error", "message": f"You do not own {shares} shares of {ticker}."}
            ROBINHOOD_SANDBOX["portfolio"][ticker]["shares"] -= shares
            ROBINHOOD_SANDBOX["cash_balance"] += total_cost

        record = {"ticker": ticker, "action": action, "shares": shares, "price": price, "total": total_cost}
        ROBINHOOD_SANDBOX["trade_history"].append(record)
        return {
            "status": "success",
            "message": f"Successfully executed {action} {shares} {ticker} at ${price} on Robinhood.",
            "remaining_cash": ROBINHOOD_SANDBOX["cash_balance"],
            "portfolio": ROBINHOOD_SANDBOX["portfolio"]
        }

    elif tool_name == "solana_agentic_dca":
        dest = arguments.get("destination_wallet", "Vote111111111111111111111111111111111111111")
        amount = float(arguments.get("sol_amount", 0.05))
        return solana_agent.execute_agent_dca_transfer(dest, amount)

    elif tool_name == "solana_record_attestation":
        return solana_agent.record_advice_on_chain(
            arguments.get("symbol", "SOL"),
            arguments.get("baseline_price", 0.0),
            arguments.get("advice", "Hold position")
        )

    return {"error": f"Tool '{tool_name}' not recognized."}